// UserDBテストリクエスト
@prod = https://guarded-savannah-05576.herokuapp.com
@dev = http://localhost:3000


### ユーザー登録
POST https://pepup.life/act_fact
content-type: application/json
cookie: pepup_sess=aaf6527eb82578a789ec05a5ca9e26ff;

{
  "id":17735342,
  "user_id":1124581825608249344,
  "act_thing_id":1,
  "date":"2019-11-27",
  "created_at":"2019-12-01T13:51:05.924+09:00",
  "updated_at":"2019-12-01T13:51:05.924+09:00"
}

### ユーザー登録
POST https://guarded-savannah-05576.herokuapp.com/api/v1/user
content-type: application/json

{
    "name": "Shohey",
    "winNum": 0,
    "loseNum": 1
}

### ユーザー全件取得
GET http://localhost:3000/api/v1/user/

@userId = 5d21d4914b7c5c04b4a9e232
### 

GET https://guarded-savannah-05576.herokuapp.com/api/v1/user/

### 指定IDのユーザー取得
GET http://localhost:3000/api/v1/user/{{userId}}

### 指定IDのユーザー削除
DELETE http://localhost:3000/api/v1/user/{{userId}}

### カテゴリ登録
POST {{prod}}/api/v1/category
content-type: application/json

{
    "name": "Service"
}

### カテゴリ全件取得
GET http://localhost:3000/api/v1/category


### イベント登録
POST http://localhost:3000/api/v1/event
content-type: application/json

{
  "no": 7,
  "name": "紐づきありテスト7イベント",
  "destinations": ["東京", "千葉"],
  "dateFrom": "2019-07-13",
  "dateTo": "2019-07-14",
  "participants": [
    {
      "userId": "5dda57fcce8cb52e98630723"
    },{
      "userId": "5d21d5164b7c5c04b4a9e235"
    },{
      "userId": "5d21d51e4b7c5c04b4a9e236"
    },{
      "userId": "5d21d52f4b7c5c04b4a9e237"
    }
  ]
}

{
  "no": 7,
  "name": "紐づきありテスト7イベント",
  "destinations": ["東京", "千葉"],
  "dateFrom": "2019-07-13",
  "dateTo": "2019-07-14",
  "participants": [
    {
      "userId": "5dda57fcce8cb52e98630723"
    },{
      "userId": "5d21d5164b7c5c04b4a9e235"
    },{
      "userId": "5d21d51e4b7c5c04b4a9e236"
    },{
      "userId": "5d21d52f4b7c5c04b4a9e237"
    }
  ]
}

### イベント全件取得
GET http://localhost:3000/api/v1/event

@eventId = 5d32ca866ab59141c4bb0440
@userId = 5d21d4914b7c5c04b4a9e232

### ID指定のイベント取得
GET http://localhost:3000/api/v1/event/{{eventId}}

### 漢気ポイント登録
POST http://localhost:3000/api/v1/point
content-type: application/json

{
  "no": 16,
  "eventId": "{{eventId}}",
  "userId": "{{userId}}",
  "point": 1000
}

### 漢気ポイント全件取得
GET http://localhost:3000/api/v1/point/{{eventId}}

###
GET https://www.mwclosangeles.com/wp-admin/admin-ajax.php?action=agenda_data&day=1609&mp=false&lang=en
